fix(qa): add -r flag to xargs to prevent errors when no JSON files found

diff --git a/.github/workflows/callable-qa.yml b/.github/workflows/callable-qa.yml
--- a/.github/workflows/callable-qa.yml
+++ b/.github/workflows/callable-qa.yml
@@ -114,7 +114,7 @@ jobs:
             - name: JSON files are valid
               if: "always() && steps.checkout.outcome == 'success'"
               run: |
-                ERRORS=$(find * -name '*.json' | xargs -n1 -P0 bash -c 'ERR=$(cd / && python -mjson.tool '$(pwd)'/"$0" 2>&1 1> /dev/null) || echo \\n::error file="$0",line=`echo "${ERR#*: line }" | cut -d" " -f 1`::${ERR%%: line *}')
+                ERRORS=$(find * -name '*.json' | xargs -r -n1 -P0 bash -c 'ERR=$(python -mjson.tool "$1" 2>&1 1> /dev/null) || echo \\n::error file="$1",line=`echo "${ERR#*: line }" | cut -d" " -f 1`::${ERR%%: line *}' _)
                 if [[ "" != "$ERRORS" ]]; then echo -e "$ERRORS\n"; exit 1; fi
             - name: YAML files are valid
               if: "always() && steps.checkout.outcome == 'success'"
